export const SIGN_IN_REQ = "SIGN_IN_REQ";
export const SIGN_UP_REQ = "SIGN_UP_REQ";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_OUT_REQ = "SIGN_OUT_REQ";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";

export const AUTH_ERROR = "AUTH_ERROR";

export const TEST_INIT_REQ = "TEST_INIT_REQ";
export const TEST_INIT_SUCCESS = "TEST_INIT_SUCCESS";

export const DEACTIVATE_TEST = "DEACTIVATE_TEST";

export const DEACTIVATE_TEST_SUCCESS = "DEACTIVATE_TEST_SUCCESS";
