export const SIGN_IN_REQ = "SIGN_IN_REQ";
export const SIGN_UP_REQ = "SIGN_UP_REQ";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_OUT_REQ = "SIGN_OUT_REQ";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";

export const AUTH_ERROR_REG = "AUTH_ERROR";
export const AUTH_ERROR_LOG = "AUTH_ERROR_LOG";

export const GET_PARTICIPANTS = "GET_PARTICIPANTS";
export const GET_PARTICIPANTS_SUCCESS = "GET_PARTICIPANTS_SUCCESS";

export const TEST_INIT_REQ = "TEST_INIT_REQ";
export const TEST_INIT_SUCCESS = "TEST_INIT_SUCCESS";

export const DEACTIVATE_TEST = "DEACTIVATE_TEST";

export const DEACTIVATE_TEST_SUCCESS = "DEACTIVATE_TEST_SUCCESS";

export const FETCHALL_TEST = "FETCHALL_TEST";
export const FETCH_ALL_SUCCESS = "FETCH_ALL_SUCCESS";

export const TEST_EDIT_REQ = "TEST_EDIT_REQ";
export const TEST_EDIT_SUCCESS = "TEST_EDIT_SUCCESS";

export const GET_TEST = "GET_TEST";
export const GET_TEST_SUCCESS = "GET_TEST_SUCCESS";
export const DELETE_TEST = "DELETE_TEST";

export const ADD_QUE_REQ = "ADD_QUE_REQ";
export const EDIT_QUE = "EDIT_QUE";
export const DEL_QUE_REQ = "DEL_QUE_REQ";

export const GET_INVITES = "GET_INVITES";
export const CREATE_INVITE = "CREATE_INVITE";
export const INVITE_SUCCESS = "CREATE_INVITE_SUCCESS";
export const SET_INVITE_CODE = "SET_INVITE_CODE";
